import LessonPage from '@/features/lesson/pages/lesson-page';
import { FeedWrapper } from '@/shared/components/atoms/feed-wrapper';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Kursus',
  description: 'Generated by create next app',
};

export default function Home() {

  return (
    <>
    <LessonPage/>
     <FeedWrapper>

     </FeedWrapper>
    </>
  );
}
