import LessonPage from '@/features/lesson/pages/lesson-page';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Kursus',
  description: 'Generated by create next app',
};

export default function Home() {

  return (
    <>
    <LessonPage/>
     
    </>
  );
}
