import CourseSectionList from '@/features/course/components/organisms/course-section-list';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Courses | Kursus',
  description: 'Generated by create next app',
};

export default function Page() {

  return (
    <CourseSectionList/>
  );
}
